# SPDX-FileCopyrightText: 2023 Katharina Fey <kookie@spacekookie.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later WITH LicenseRef-AppStore

[package]
name = "libratman"
description = "Ratman types, client, and interface library"
version = "0.6.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
## TODO: figure out if it makes sense to disable one or both of these features by default
default = [ "client", "netmod" ]
netmod = [ ]
client = [ ]
metrics = [ "prometheus-client" ]
daemon = [ ]

[dependencies]
async-eris = { version = "0.1", path = "../../utils/eris-rs" }
async-trait = "0.1"
bincode = "1.0"
blake2 = "0.9.0"
byteorder = "1.0"
bytes = "1.5"
cfg-if = "1.0"
chrono = { version = "0.4", features = ["serde"] }
directories = "4.0"
ed25519-dalek = "1.0.0"
fjall = "1.0" # only needed for error handling
flate2 = "1.0"
futures = "0.3"
hex = "0.4"
itertools = "0.13"
nix = "0.23"
nom = "7.0"
once_cell = "1.0"
prometheus-client = { version = "0.16", optional = true }
rand = "0.7"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
static_assertions = "1.0"
thiserror = "1.0"
tokio = { version = "1.0", features = [ "full", "rt", "fs", "io-util", "macros", "io-std", "net", "time", "process", "sync", "signal", "parking_lot" ] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features=[ "compat" ] }
tracing = "0.1"
tracing-subscriber = "0.2"
twox-hash = "1.5"

[dev-dependencies]
serde_json = "1.0"

# [package.metadata.docs.rs]
# no-default-features = true
